services:
  backend:
    container_name: backend
    image: docker.io/desoprotocol/backend:stable
    command: run
    volumes:
    - testnet-db:/db
    ports:
    - 18001:18001
    - 18000:18000
    - 2345:2345
    environment:
    # Values we set here OVERRIDE the base.env variables.
    #
    # Set the seed here if you want to be a validator
    # - POS_VALIDATOR_SEED=
    #
    # For testnet, we must use a different checkpoint provider
    - GLOG_V=1
    - TRUSTED_BLOCK_PRODUCER_START_HEIGHT=2000000000
    - FORCE_CHECKSUM=false
    - SYNC_TYPE=blocksync
    - CHECKPOINT_SYNCING_PROVIDERS=https://test.deso.org
    - TESTNET=true
    # The REGTEST param is the main difference between running a testnet vs devnet node.
    - REGTEST=false
    - CONNECT_IPS=dorsey.bitclout.com:18000
    - PROTOCOL_PORT=18000
    - API_PORT=18001
    env_file:
    - base.env
    expose:
    - "18001"
    - "18000"
    - "2345"
  frontend:
    container_name: frontend 
    image: docker.io/desoprotocol/frontend:stable
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    env_file:
    # TODO: We should break the frontend params from the backend params.
    - base.env
    expose:
    - "8080"
  nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
    depends_on: 
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
volumes:
  testnet-db:
